// electron/main/sync/lexorank.ts
// A lexicographic fractional ordering key ("LexoRank"-style), used as `sync_order` on
// `todo_states` and `todo_projects` (FR-011, scope corrected -- see the tactical plan's Summary:
// `todo_labels` has no ordering at all).
//
// Float-based fractional indexing exhausts precision after roughly 50 halvings between the same
// neighbors, producing real collisions (`strapi#22015`). Using base-36 strings instead of floats
// sidesteps this entirely: when there is no room between two adjacent keys at the current
// length, the generator extends the key's length rather than reusing a value, and two distinct
// keys generated by this module can never compare equal.

const ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyz";
const BASE = ALPHABET.length; // 36

function digitValue(c: string): number {
  const v = ALPHABET.indexOf(c);
  if (v === -1) throw new Error(`lexorank: invalid character "${c}"`);
  return v;
}

function digitChar(v: number): string {
  const c = ALPHABET[v];
  if (c === undefined) throw new Error(`lexorank: digit ${v} out of range`);
  return c;
}

function toDigits(s: string): number[] {
  return [...s].map(digitValue);
}

function fromDigits(digits: number[]): string {
  return digits.map(digitChar).join("");
}

/**
 * Generates a key that sorts strictly between `lower` and `upper`. Either bound may be `null`,
 * meaning "no bound on this side" (start of the list / end of the list). Throws if `lower` does
 * not sort strictly before `upper`, since there would be nothing to generate.
 */
export function keyBetween(lower: string | null, upper: string | null): string {
  if (lower !== null && upper !== null && lower >= upper) {
    throw new Error(`lexorank.keyBetween: lower (${lower}) must sort strictly before upper (${upper})`);
  }

  const loDigits = lower === null ? [] : toDigits(lower);
  const hiDigits = upper === null ? null : toDigits(upper);

  const result: number[] = [];
  let boundedAbove = hiDigits !== null;
  let i = 0;
  for (;;) {
    const loD = i < loDigits.length ? loDigits[i]! : 0;
    const hiD = boundedAbove && hiDigits !== null && i < hiDigits.length ? hiDigits[i]! : BASE;

    if (hiD - loD >= 2) {
      result.push(loD + Math.floor((hiD - loD) / 2));
      break;
    }

    result.push(loD);
    // Once a strictly smaller digit has been placed relative to `upper` at this depth, every
    // string with this prefix already sorts below `upper` regardless of what follows -- so
    // `upper` no longer bounds anything deeper, and only `lower` still needs to be beaten.
    if (hiD - loD === 1) boundedAbove = false;
    i += 1;
  }

  return fromDigits(result);
}

/** The conventional first key when a list has no ordering yet: the alphabet's own midpoint. */
export function initialKey(): string {
  return keyBetween(null, null);
}

/**
 * Generates `count` strictly increasing keys in one call -- used to give a freshly reordered
 * list a brand new set of `sync_order` values, one call per full local reorder (mirroring the
 * "rewrite the whole list" shape `reorderTodoStates`/`reorderTodoProjects` already produce).
 */
export function generateOrderedKeys(count: number): string[] {
  const keys: string[] = [];
  let prev: string | null = null;
  for (let i = 0; i < count; i++) {
    const key = keyBetween(prev, null);
    keys.push(key);
    prev = key;
  }
  return keys;
}
